# chatterbot_settings.yaml

secret_key: 'your_secret_key_here'
debug: True
allowed_hosts:
  - 'localhost'
  - '127.0.0.1'
  - '[::1]'

chatterbot:
  name: 'Fruit Shop Lin'
  logic_adapters:
    - import_path: 'chatterbot.logic.BestMatch'
      default_response: '非常抱歉，我未能理解您的意思。'
      maximum_similarity_threshold: 0.90
  data:
    - ['你好', '您好，有什麼可以為您效勞的呢?']
    - ['再見', '再見，祝您有美好的一天。']
    - ['可以幫我找到某種水果嗎？', '當然，請告訴我您需要什麼水果。']
    - ['今天有什麼特價水果嗎？', '今天我們的特價水果有蘋果和香蕉。']
    - ['您有橙子嗎？', '是的，我們有新鮮的橙子。']
    - ['一公斤蘋果多少錢？', '一公斤蘋果是100元。']
    - ['你們有機會送貨服務嗎？', '是的，我們提供送貨服務。']
    - ['送貨費用多少？', '送貨費用根據距離計算，起價50元。']
    - ['可以用信用卡付款嗎？', '是的，我們接受信用卡付款。']
    - ['營業時間是什麼時候？', '我們的營業時間是每天早上8點到晚上8點。']
    - ['有沒有優惠券？', '目前我們有10%的優惠券，購買時請使用代碼「FRUIT10」。']
    - ['請問你們的地址是什麼？', '我們的地址是台北市中正區仁愛路100號。']
    - ['有機水果嗎？', '是的，我們有多種有機水果供應。']
    - ['有沒有打折的水果？', '今天打折的水果有葡萄和草莓。']
    - ['可以幫我推薦一些季節水果嗎？', '當然，目前的季節水果有芒果和西瓜。']
    - ['需要提前訂購嗎？', '如果您需要大量購買，建議提前訂購。']
    - ['可以退貨嗎？', '如果水果有質量問題，我們會提供退貨服務。']
    - ['有沒有禮品籃？', '是的，我們提供多種水果禮品籃選擇。']
    - ['你們的電話號碼是什麼？', '我們的聯絡電話是0903936679，或者是line call免費通話。']
    - ['謝謝您的幫忙。', '不客氣，很高興能幫助您。']
    - ['您可以重複一下嗎？', '當然，我們提供的服務包括新鮮水果銷售、送貨服務和優惠活動。']
    - ['有沒有當季水果的促銷活動？', '我們目前有針對當季水果的特價活動，請隨時關注我們的促銷訊息。']
