# -*- coding: utf-8 -*-

"""
Django settings for your_projec_line project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@^l38*7mq8@d0i@$6=^v==&y8)t#pdw7_nbvva1542u8&4b0ra'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chatterbot_app',  # 確保你的應用程式名稱正確
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'your_projec_line.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'your_projec_line.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ChatterBot settings
CHATTERBOT = {
    'name': 'Fruit Shop Lin',
    'logic_adapters': [
        {
            'import_path': 'chatterbot.logic.BestMatch',
            'default_response': '非常抱歉，我未能理解您的意思。',
            'maximum_similarity_threshold': 0.90
        }
    ],
    'data': [
        ['你好', '您好，有什麼可以為您效勞的呢?'],
        ['再見', '再見，祝您有美好的一天。'],
        ['可以幫我找到某種水果嗎？', '當然，請告訴我您需要什麼水果。'],
        ['今天有什麼特價水果嗎？', '今天我們的特價水果有蘋果和香蕉。'],
        ['您有橙子嗎？', '是的，我們有新鮮的橙子。'],
        ['一公斤蘋果多少錢？', '一公斤蘋果是100元。'],
        ['你們有機會送貨服務嗎？', '是的，我們提供送貨服務。'],
        ['送貨費用多少？', '送貨費用根據距離計算，起價50元。'],
        ['可以用信用卡付款嗎？', '是的，我們接受信用卡付款。'],
        ['營業時間是什麼時候？', '我們的營業時間是每天早上8點到晚上8點。'],
        ['有沒有優惠券？', '目前我們有10%的優惠券，購買時請使用代碼「FRUIT10」。'],
        ['請問你們的地址是什麼？', '我們的地址是台北市中正區仁愛路100號。'],
        ['有機水果嗎？', '是的，我們有多種有機水果供應。'],
        ['有沒有打折的水果？', '今天打折的水果有葡萄和草莓。'],
        ['可以幫我推薦一些季節水果嗎？', '當然，目前的季節水果有芒果和西瓜。'],
        ['需要提前訂購嗎？', '如果您需要大量購買，建議提前訂購。'],
        ['可以退貨嗎？', '如果水果有質量問題，我們會提供退貨服務。'],
        ['有沒有禮品籃？', '是的，我們提供多種水果禮品籃選擇。'],
        ['你們的電話號碼是什麼？', '我們的聯絡電話是0903936679，或者打line call免費通話。'],
        ['謝謝您的幫忙。', '不客氣，很高興能幫助您。'],
        ['您可以重複一下嗎？', '當然，我們提供的服務包括新鮮水果銷售、送貨服務和優惠活動。'],
        ['有沒有當季水果的促銷活動？', '我們目前有針對當季水果的特價活動，請隨時關注我們的促銷訊息。']
    ]
}
