name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Heroku CLI
        uses: heroku/actions/setup-cli@v7
        with:
          heroku-api-key: ${{ secrets.HEROKU_API_KEY }}

      - name: Login to Heroku
        run: heroku auth:token

      - name: Deploy to Heroku
        env:
          LINE_CHANNEL_ID: ${{ secrets.LINE_CHANNEL_ID }}
          LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
        run: |
          git push heroku main
